import { useEffect, useState } from "react"

type Mission = {
  id: number
    title: string
      description: string
        impact: string
          reward: number
          }

          export default function Missions() {
            const [missions, setMissions] = useState<Mission[]>([])

              useEffect(() => {
                  setMissions([
                        {
                                id: 1,
                                        title: "Aiuta una persona oggi",
                                                description:
                                                          "Fai qualcosa di concreto per aiutare qualcuno nella vita reale e raccontalo alla community.",
                                                                  impact: "Sociale",
                                                                          reward: 10
                                                                                },
                                                                                      {
                                                                                              id: 2,
                                                                                                      title: "Riduci uno spreco",
                                                                                                              description:
                                                                                                                        "Individua uno spreco nella tua vita quotidiana e cambialo realmente.",
                                                                                                                                impact: "Ambientale",
                                                                                                                                        reward: 12
                                                                                                                                              },
                                                                                                                                                    {
                                                                                                                                                            id: 3,
                                                                                                                                                                    title: "Condividi conoscenza utile",
                                                                                                                                                                            description:
                                                                                                                                                                                      "Insegna qualcosa di pratico alla community o a una persona.",
                                                                                                                                                                                              impact: "Culturale",
                                                                                                                                                                                                      reward: 14
                                                                                                                                                                                                            },
                                                                                                                                                                                                                  {
                                                                                                                                                                                                                          id: 4,
                                                                                                                                                                                                                                  title: "Migliora uno spazio",
                                                                                                                                                                                                                                          description:
                                                                                                                                                                                                                                                    "Sistema, pulisci o migliora un piccolo spazio che usano anche altri.",
                                                                                                                                                                                                                                                            impact: "Comunità",
                                                                                                                                                                                                                                                                    reward: 18
                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                        id: 5,
                                                                                                                                                                                                                                                                                                title: "Riduci consumo inutile",
                                                                                                                                                                                                                                                                                                        description:
                                                                                                                                                                                                                                                                                                                  "Riduci un'abitudine che genera spreco (energia, plastica, tempo).",
                                                                                                                                                                                                                                                                                                                          impact: "Ambientale",
                                                                                                                                                                                                                                                                                                                                  reward: 15
                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                      id: 6,
                                                                                                                                                                                                                                                                                                                                                              title: "Supporta un progetto locale",
                                                                                                                                                                                                                                                                                                                                                                      description:
                                                                                                                                                                                                                                                                                                                                                                                "Aiuta o promuovi un progetto positivo nella tua città.",
                                                                                                                                                                                                                                                                                                                                                                                        impact: "Sociale",
                                                                                                                                                                                                                                                                                                                                                                                                reward: 20
                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                    id: 7,
                                                                                                                                                                                                                                                                                                                                                                                                                            title: "Connetti due persone",
                                                                                                                                                                                                                                                                                                                                                                                                                                    description:
                                                                                                                                                                                                                                                                                                                                                                                                                                              "Metti in contatto due persone che possono aiutarsi a vicenda.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      impact: "Relazionale",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              reward: 16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: "Documenta una soluzione",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Mostra una soluzione concreta a un problema reale.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    impact: "Innovazione",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reward: 22
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 9,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: "Riduci un problema locale",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Intervieni attivamente su un problema della tua zona.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  impact: "Civico",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          reward: 25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: "Genera impatto collettivo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Coinvolgi almeno altre 2 persone in un'azione positiva.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                impact: "Comunità",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reward: 30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "#0f0f0f",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #222"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 style={{ marginBottom: 20 }}>Missioni Correnti</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {missions.map((mission) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={mission.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid #2a2a2a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#151515"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>{mission.title}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ opacity: 0.9 }}>{mission.description}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: "space-between",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Impatto: {mission.impact}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>{mission.reward} CANCELLIERE</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }