import { create } from "zustand"

export type Mission = {
  id: string
    title: string
      description: string
        impact: string
          reward: number
            completed: boolean
            }

            type MissionState = {
              wallet: number
                missions: Mission[]
                  completeMission: (id: string) => void
                  }

                  export const useMissionStore = create<MissionState>((set) => ({
                    wallet: 120,

                      missions: [
                          {
                                id: "m1",
                                      title: "Aiuta una persona oggi",
                                            description:
                                                    "Fai qualcosa di concreto per aiutare qualcuno nella vita reale e raccontalo alla community.",
                                                          impact: "Sociale",
                                                                reward: 10,
                                                                      completed: false
                                                                          },
                                                                              {
                                                                                    id: "m2",
                                                                                          title: "Riduci uno spreco",
                                                                                                description:
                                                                                                        "Individua uno spreco nella tua vita quotidiana e cambialo realmente.",
                                                                                                              impact: "Ambientale",
                                                                                                                    reward: 12,
                                                                                                                          completed: false
                                                                                                                              },
                                                                                                                                  {
                                                                                                                                        id: "m3",
                                                                                                                                              title: "Condividi conoscenza utile",
                                                                                                                                                    description:
                                                                                                                                                            "Spiega qualcosa che sai fare e che può aiutare altre persone.",
                                                                                                                                                                  impact: "Culturale",
                                                                                                                                                                        reward: 15,
                                                                                                                                                                              completed: false
                                                                                                                                                                                  },
                                                                                                                                                                                      {
                                                                                                                                                                                            id: "m4",
                                                                                                                                                                                                  title: "Migliora qualcosa intorno a te",
                                                                                                                                                                                                        description:
                                                                                                                                                                                                                "Sistema, pulisci o migliora uno spazio reale.",
                                                                                                                                                                                                                      impact: "Ambientale",
                                                                                                                                                                                                                            reward: 18,
                                                                                                                                                                                                                                  completed: false
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                id: "m5",
                                                                                                                                                                                                                                                      title: "Supporta un progetto",
                                                                                                                                                                                                                                                            description:
                                                                                                                                                                                                                                                                    "Aiuta un progetto o una persona a fare un passo avanti.",
                                                                                                                                                                                                                                                                          impact: "Sociale",
                                                                                                                                                                                                                                                                                reward: 20,
                                                                                                                                                                                                                                                                                      completed: false
                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                    id: "m6",
                                                                                                                                                                                                                                                                                                          title: "Impara qualcosa di nuovo",
                                                                                                                                                                                                                                                                                                                description:
                                                                                                                                                                                                                                                                                                                        "Dedica tempo a imparare una competenza reale.",
                                                                                                                                                                                                                                                                                                                              impact: "Crescita",
                                                                                                                                                                                                                                                                                                                                    reward: 14,
                                                                                                                                                                                                                                                                                                                                          completed: false
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                        id: "m7",
                                                                                                                                                                                                                                                                                                                                                              title: "Diffondi un'idea positiva",
                                                                                                                                                                                                                                                                                                                                                                    description:
                                                                                                                                                                                                                                                                                                                                                                            "Condividi un messaggio o contenuto che migliori la community.",
                                                                                                                                                                                                                                                                                                                                                                                  impact: "Culturale",
                                                                                                                                                                                                                                                                                                                                                                                        reward: 11,
                                                                                                                                                                                                                                                                                                                                                                                              completed: false
                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                            id: "m8",
                                                                                                                                                                                                                                                                                                                                                                                                                  title: "Riduci l'impatto digitale",
                                                                                                                                                                                                                                                                                                                                                                                                                        description:
                                                                                                                                                                                                                                                                                                                                                                                                                                "Elimina contenuti inutili o organizza meglio il tuo spazio digitale.",
                                                                                                                                                                                                                                                                                                                                                                                                                                      impact: "Digitale",
                                                                                                                                                                                                                                                                                                                                                                                                                                            reward: 9,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  completed: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: "m9",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: "Collabora con qualcuno",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Lavora con un'altra persona su qualcosa di utile.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          impact: "Sociale",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reward: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      completed: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: "m10",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: "Crea valore reale",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Produci qualcosa che possa aiutare altre persone.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              impact: "Economico",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reward: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completed: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  completeMission: (id) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      set((state) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const mission = state.missions.find((m) => m.id === id)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!mission || mission.completed) return state

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wallet: state.wallet + mission.reward,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        missions: state.missions.map((m) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  m.id === id ? { ...m, completed: true } : m
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }))